[build]
publish = "public"
command = "make build; hugo --minify"

[context.production.environment]
HUGO_VERSION = "0.47.1"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.split1]
command = "make build; hugo --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.47.1"
HUGO_ENV = "production"

[context.deploy-preview]
command = "make build; hugo --buildFuture -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.47.1"

[context.branch-deploy]
command = "make build; hugo -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.47.1"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"
